import './pharma.js'
import './Summary/Summary.js'
import './MarketOverview/MarketOverview.js'
import './CompetitorAnalysis/CompetitorAnalysis.js'
import './PatientsJourney/PatientsJourney.js'
import './ComorbidityAnalytics/ComorbidityAnalytics.js'
import './DrugOccurance/DrugOccurance.js';
import './OtherMedicineCount/OtherMedicineCount.js';
import './Cost/MedicationCost.js';
import './AdvanceAnalytics/AdvanceAnalytics.js';
import './PharmaSubTabs/pharmaSubTabs.js';
import './RWEBenchmark/RWEBenchmark.js';
import './PhysicianPatientTarget/PhysicianPatientTarget.js';
import './pharmaLib.js';