import './login';
import './patient-tabs'
import './patient';
import './searchpateint';
import './provider';
import './payer';
import './pharma';
import './analytics';
import './safety';
import './cost';
import './compareDrug';
import './compareDrugRWE';
import './adminDashboard';
import './advancedsearch';
import './covermymeds';
import './parequest';
import './cmm';
//import './dashboard';