import './3DstocChartJS.js';
import './app.min.js';
import './bootstrap.min.js';
import './circosJS.js';
import './demo.js';
import './icheck.js';
import './jquery-ui.min.js';
import './jquery.idle.min.js';
import './jquery.dataTables.js';
import './jquery.knob.js';
import './jquery.placeholder.min.js';
import './jquery.sortelements.js';
import './jquery.validate.min.js';
import './zrotation.js';
import './pathseg.js';
import './tag-it.min.js';
import './jquery.bdt.min.js';
//import './new_mockups';
import './rotate.js'
import './jquery.toast.min.js'

import './bootstrap-table.js';
import './jquery.multiselect.js';
import './daterangepicker.js';
import './daterangepicker.css';
